language: csharp
solution: LabWork1.sln
sudo: required
mono: none
dotnet: 2.0.0
dist: trusty
before_script:
- chmod a+x ./build.sh
- chmod a+x ./test.sh
jobs:
  include:
  - stage: build
    script: "./build.sh"
  - stage: test
    script: "./test.sh"
  - stage: deploy
    script: skip
deploy:
  provider: azure_web_apps
  username: gail64917@yandex.ru      
  password: secret_password
  site: http://lr120170914065559.azurewebsites.net
